const assert=require('node:assert/strict');
const Buffer=require('../chrome-extension/transcript_buffer.js');
const spoken=[];let cancelled=0;
const b=new Buffer(text=>spoken.push(text),()=>cancelled++);
const output=(id,text)=>b.consume({type:'output_transcript.added',item:{id,text}});
const start=(id,text)=>b.consume({type:'turn.created',turn:{id,role:'assistant',transcript:text}});
const done=(id,text)=>b.consume({type:'turn.done',turn:{id,role:'assistant',transcript:text}});
output('one',' 안녕하세요');start('a',' 안녕하세요');
output('two','. 이렇게');output('two','. 이렇게');output('three',' 만나서 반가워요.');
assert.equal(spoken.length,1,'Adjacent short sentences can start as soon as they form a useful phrase');
done('a',' 안녕하세요. 이렇게 만나서 반가워요.');
assert.deepEqual(spoken,['안녕하세요. 이렇게 만나서 반가워요.']);
output('four',' 가격은 3.14');start('b',' 가격은 3.14');
done('b',' 가격은 3.14원입니다');
assert.equal(spoken[1],'가격은 3.14원입니다');
output('five',' 버릴 문장');start('c',' 버릴 문장');
b.consume({type:'input_transcript.added',item:{text:'멈춰'}});
b.consume({type:'input_transcript.added',item:{text:'주세요'}});
assert.equal(cancelled,1);
done('c',' 버릴 문장입니다.');
b.consume({type:'turn.done',turn:{id:'user1',role:'user'}});
output('six',' 새 답변');start('d',' 새 답변');output('seven','이에요.');done('d',' 새 답변이에요.');
assert.equal(spoken[2],'새 답변이에요.');assert.equal(spoken.length,3);
b.consume({type:'input_transcript.added',item:{text:'다시'}});
b.consume({type:'output_transcript.added',start_ms:41600,end_ms:41800,item:{id:'eight',text:' 어'}});
b.consume({type:'output_transcript.added',start_ms:41800,end_ms:42000,item:{id:'nine',text:'땠'}});
b.consume({type:'turn.created',turn:{id:'e',role:'assistant',start_ms:41800,transcript:' 어'}});
output('ten','어?');done('e',' 어땠어?');
assert.equal(spoken[3],'어땠어?');
const grouped=[];const g=new Buffer(text=>grouped.push(text),()=>{});
const two='오늘 만나서 반가워. 너랑 같이 재미있는 이야기를 나누고 싶었어. 오늘은 무슨 일이 있었어?';
g.append(two);g.flushText(true);
assert.equal(grouped.join(' '),two);
assert.ok(grouped[0].includes('반가워.')&&grouped[0].includes('싶었어.'),'The first two sentences should stay together');
const quick=[];const q=new Buffer(text=>quick.push(text),()=>{});
q.append('오늘은 어땠어?');assert.deepEqual(quick,['오늘은 어땠어?'],'Start a useful short opening immediately');
q.append('네 이야기를 편하게 들려주면 좋겠어.');
assert.equal(quick.length,2,'Later complete sentences must not wait for a second sentence');
const linked=[];const link=new Buffer(text=>linked.push(text),()=>{});
link.append('오늘은 네가 이야기하고 싶은 주제부터 편하게 같이 이야기해 보면 좋을 것 같아.');
assert.equal(linked.length,1,'A complete first sentence must not wait for the second sentence');
link.append(' 어떤 이야기부터 시작해 볼까?');
assert.equal(linked.length,1,'Later short sentences can gather context');link.flushText(true);
assert.equal(linked.length,2);assert.ok(linked[1].endsWith('시작해 볼까?'));
const early=[];const next=new Buffer(text=>early.push(text),()=>{});
for(const id of ['first','second']){
  next.consume({type:'turn.created',turn:{id,role:'assistant',transcript:''}});
  next.append('오늘은 편하게 이야기해 보면 좋겠어.');
  assert.equal(early.length,id==='first'?1:2,'Every new reply gets the short first-sentence threshold');
  next.consume({type:'turn.done',turn:{id,role:'assistant',transcript:'오늘은 편하게 이야기해 보면 좋겠어.'}});
}
const long=[];const c=new Buffer(text=>long.push(text),()=>{});
c.append('가'.repeat(350));c.flushText(true);
assert.equal(long.join(''),'가'.repeat(350));assert.ok(long.every(x=>x.length<=140));
console.log('transcript batching, duplicate recovery and interruption tests passed');
